openapi: 3.0.0
info:
  title: Student API
  version: 1.0.0

paths:
  /students:
    get:
      summary: Get students
      responses:
        "200":
          description: Success

    post:
      summary: Create student
      responses:
        "201":
          description: Created

  /students/{id}:
    get:
      summary: Get student by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Success

    delete:
      summary: Delete student
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Deleted
